from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('custom-admin/', views.admin_login, name='admin_login'),
    path('custom-admin/verify-otp/', views.admin_verify_otp, name='admin_verify_otp'),
    path('custom-admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('custom-admin/users/', views.admin_users, name='admin_users'),
    path('custom-admin/users/add/', views.admin_add_user, name='admin_add_user'),
    path('custom-admin/courses/', views.admin_courses, name='admin_courses'),
    path('custom-admin/course/create/', views.admin_course_create, name='admin_course_create'),
    path('custom-admin/course/<slug:slug>/edit/', views.admin_course_edit, name='admin_course_edit'),
    path('custom-admin/course/<slug:slug>/delete/', views.admin_course_delete, name='admin_course_delete'),
    path('custom-admin/course/<slug:slug>/content/', views.admin_course_content, name='admin_course_content'),
    path('custom-admin/logout/', views.admin_logout, name='admin_logout'),
    path('topic/<slug:slug>/', views.topic_detail, name='topic_detail'),
    path('course/<slug:slug>/', views.course_detail, name='course_detail'),
    path('course/<slug:slug>/rate/', views.submit_course_rating, name='submit_course_rating'),
    path('courses/', views.course_list, name='course_list'),
    path('course/review/<int:rating_id>/delete/', views.delete_course_rating, name='delete_course_rating'),
    path('search/', views.search_courses, name='search_courses'),
    path('course/<slug:slug>/enroll/', views.enroll_course, name='enroll_course'),
    path('course/<slug:slug>/content/', views.course_content, name='course_content'),
    path('complete-lesson/<int:lesson_id>/', views.complete_lesson, name='complete_lesson'),
]