# Generated by Django 5.1.2 on 2024-12-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_topic_options_remove_topic_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='main_category',
            field=models.CharField(choices=[('technology', 'Technology'), ('school', 'School'), ('finance', 'Finance'), ('music', 'Music'), ('lifestyle', 'Lifestyle'), ('video_photo', 'Video & Photography')], max_length=50),
        ),
    ]
