# Generated by Django 5.1.2 on 2024-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_course_enrolled_students_alter_lesson_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('business', 'Business'), ('finance', 'Finance & Accounting'), ('it', 'IT & Software'), ('design', 'Design'), ('marketing', 'Marketing'), ('lifestyle', 'Lifestyle'), ('photography', 'Photography & Video'), ('health', 'Health & Fitness'), ('music', 'Music'), ('teaching', 'Teaching & Academics')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
