# Generated by Django 5.1.2 on 2024-12-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_topic_icon_alter_topic_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserating',
            name='review',
        ),
        migrations.AddField(
            model_name='courserating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
