# Generated by Django 5.1.2 on 2024-12-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_profile_image_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'ordering': ['-created_at']},
        ),
    ]
