# Generated by Django 5.1.2 on 2024-12-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_topic_created_at_remove_topic_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('business', 'Business'), ('finance', 'Finance & Accounting'), ('it', 'IT & Software'), ('design', 'Design'), ('marketing', 'Marketing'), ('lifestyle', 'Lifestyle'), ('photography', 'Photography & Video'), ('health', 'Health & Fitness'), ('music', 'Music'), ('teaching', 'Teaching & Academics')], default='development', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'category')},
        ),
    ]
