# Generated by Django 5.1.2 on 2024-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_course_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'Engleski'), ('sr', 'Srpski'), ('de', 'Nemački'), ('fr', 'Francuski'), ('es', 'Španski')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('development', 'Razvoj softvera'), ('business', 'Biznis'), ('finance', 'Finansije & Računovodstvo'), ('it', 'Infomracione tehnologije'), ('design', 'Dizajn'), ('marketing', 'Marketing'), ('lifestyle', 'Lifestyle'), ('photography', 'Fotografija & Video'), ('health', 'Zdravlje & Sport'), ('music', 'Muzika'), ('teaching', 'Pedagogija & Nauka')], default='development', max_length=50),
        ),
    ]
